#!/usr/bin/env bash
# Transfers a file from our client to a server.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ $# -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
